steps:
  - name: 'gcr.io/cloud-builders/docker' # Image prebuilt oleh Google
    args: ['build', '-t', 'gcr.io/grand-analyzer-443203-j6/fastapi-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/grand-analyzer-443203-j6/fastapi-app:latest']

images:
  - 'gcr.io/grand-analyzer-443203-j6/fastapi-app:latest'
